_extends: .github

repository:
  name: NucleosDompdfBundle
  description: 📜 This bundle provides a wrapper for using dompdf inside symfony.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, dompdf, pdf, wrapper
